### ISSUE TITLE
swimToShore hiba

### ISSUE THREAD

**Issue by kovacsmarcell** [IITeam-Rocket/IceField#30]
public void swimToShore() {
        swimToShoreStrategy.executeStrategy(this);
}
hibát dob, ha a Polarbear meghívja
Írd be a következő két commandot, hogy reprodukáld (Legyen a random on, ahogy alapból van!):
```
input map.txt
nextcharacter
```
Kövi hibát fogja dobni:
Exception in thread "main" java.lang.NullPointerException
	at models.figures.Figure.swimToShore(Figure.java:43)
	at models.tiles.Hole.acceptCharacter(Hole.java:53)
	at models.figures.Figure.moveTo(Figure.java:34)
	at models.figures.PolarBear.step(PolarBear.java:41)
	at controllers.Prototype.command_nextcharacter(Prototype.java:196)
	at controllers.Prototype.interpret(Prototype.java:930)
	at controllers.Prototype.run(Prototype.java:1010)
	at Main.main(Main.java:10)

**Comment by Tophyan1** [comment]
Csináltam konstruktort a medvének, már nem kéne, hogy ez történjen.
